name = "ai-kids"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "ai-kids-ops"
database_id = "3a0bdca7-162c-4aab-aaab-c58d4032a883"
